 ALTER MATERIALIZED VIEW MV_PORTAL_DATA_DICTIONARY_CACHE REFRESH COMPLETE START WITH TRUNC(SYSDATE+1) + 3/24  NEXT (SYSDATE+1) + 3/24 ;
/ 
 CREATE OR REPLACE VIEW GENDATADICTCACHEENTRIES AS
SELECT * FROM MV_PORTAL_DATA_DICTIONARY_CACHE ORDER BY 1;
/
