SELECT i.BRKEY,
       i.INSPKEY,
       i.INSPUSRKEY,
       i.INSPUSRGUID,
       (SELECT pau.PON_APP_USERS_GD
          FROM PON_APP_USERS pau
         WHERE TO_CHAR(pau.USERKEY) = TO_CHAR(i.INSPUSRKEY)) "CALC"
  FROM INSPEVNT i
 WHERE i.INSPUSRGUID IS NULL
    OR ISNUMERIC(i.INSPUSRGUID) = 1 --OR ISNUMERIC(i.USERKEY)=0
