--ALTER TABLE PON_APP_CONTROL_SECURITY ADD CONSTRAINT FK_CTRL_SEC_TO_NAV_CONTROL FOREIGN KEY (PON_NAV_CONTROL_GD) REFERENCES PON_NAV_CONTROL (PON_NAV_CONTROL_GD) ON DELETE CASCADE;ORA-02298: cannot validate (KDOT_BLP.FK_CTRL_SEC_TO_NAV_CONTROL) - parent keys not found

select pacs.PON_NAV_CONTROL_GD
 from PON_APP_CONTROL_SECURITY pacs LEFT OUTER JOIN PON_NAV_CONTROL pnc
ON pacs.pon_nav_control_gd = pnc.pon_nav_control_gd
WHERE pnc.pon_nav_control_gd is null;
